### ISSUE TITLE
Bug no loop (2)

### ISSUE THREAD

**Issue by SrWhale** [Gorillas-Team/Gorilink#33]
![image](https://user-images.githubusercontent.com/52763403/88585702-caa0e500-d029-11ea-9cd2-db1e188a11ec.png)

**Comment by Psykka** [comment]
I will investigate and work to fix

**Comment by Psykka** [comment]
I thought better and thought it was no longer necessary to have an index there, assuming it is always an array I believe that most users will not have problems operating them

see commit https://github.com/Gorillas-Team/Gorilink/commit/a746a4bbb7d7e0dd18dc9cec20d5c7b7e7519f38
